In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
# Load the trained model from the HDF5 file
import pickle
import pandas as pd
import numpy as np

In [2]:
##Load the ANN trained model, scalar pickle file and the one hot encoded test data for making predictions
model = load_model('churn_model.h5')
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('onehot_encoder.pkl', 'rb') as f:
    onehot_encoder_geo = pickle.load(f)
with open('label_encoder.pkl', 'rb') as f:
    label_encoder_gender = pickle.load(f)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
##Example input data for prediction (replace with actual test data)
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}
input_df = pd.DataFrame([input_data])

In [4]:
##One hot encode the 'Geography' feature using the loaded onehot encoder
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\shash\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [5]:
input_df = pd.DataFrame([input_data])
input_data = pd.concat([input_df.reset_index(drop=True), geo_encoded_df], axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [6]:
##Encode the categorical 'Gender
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
##Drop the original 'Geography' column as it's now encoded
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [7]:
##Concatinate the encoded geography columns with the original input dataframe
input_df = pd.concat([input_df.drop(columns=['Geography'], axis=1), geo_encoded_df], axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [8]:
##Scale the input data using the loaded scaler
scaled_input = scaler.transform(input_df)
scaled_input

ValueError: The feature names should match those that were passed during fit.
Feature names must be in the same order as they were in fit.