In [1]:
import numpy as np
import pandas as pd

In [2]:
##Pivot tables
my_dict = {'Size': ['S', 'M', 'L', 'XL', 'XXL', 'S', 'M', 'L', 'XL', 'XXL'],
           'type': ['Polo', 'Polo', 'Polo', 'Polo', 'Polo', 'T-shirt', 'T-shirt', 'T-shirt', 'T-shirt', 'T-shirt'],
            'Price': [500, 600, 700, 800, 900, 300, 400, 500, 600, 700],
            'Quantity': [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]}
my_dict

{'Size': ['S', 'M', 'L', 'XL', 'XXL', 'S', 'M', 'L', 'XL', 'XXL'],
 'type': ['Polo',
  'Polo',
  'Polo',
  'Polo',
  'Polo',
  'T-shirt',
  'T-shirt',
  'T-shirt',
  'T-shirt',
  'T-shirt'],
 'Price': [500, 600, 700, 800, 900, 300, 400, 500, 600, 700],
 'Quantity': [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]}

In [3]:
m = pd.DataFrame(my_dict)
m

  Size     type  Price  Quantity
0    S     Polo    500         5
1    M     Polo    600        10
2    L     Polo    700        15
3   XL     Polo    800        20
4  XXL     Polo    900        25
5    S  T-shirt    300        30
6    M  T-shirt    400        35
7    L  T-shirt    500        40
8   XL  T-shirt    600        45
9  XXL  T-shirt    700        50

In [4]:
print(m.Price)
print(m.Quantity.mean())
print(m.Price.mean())
print(m.Price.max())
print(m.Quantity.max())

0    500
1    600
2    700
3    800
4    900
5    300
6    400
7    500
8    600
9    700
Name: Price, dtype: int64
27.5
600.0
900
50

In [5]:
pd_1 = m.pivot_table(index='Size', columns='type', values='Price', aggfunc=np.mean)
pd_1

C:\Users\shash\AppData\Local\Temp\ipykernel_13936\4004346896.py:1: FutureWarning: The provided callable <function mean at 0x0000021E84557420> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd_1 = m.pivot_table(index='Size', columns='type', values='Price', aggfunc=np.mean)

type   Polo  T-shirt
Size
L     700.0    500.0
M     600.0    400.0
S     500.0    300.0
XL    800.0    600.0
XXL   900.0    700.0

In [6]:
pd_2 = m.pivot_table(index='type', columns='Size', values='Price', aggfunc=np.mean)
pd_2

C:\Users\shash\AppData\Local\Temp\ipykernel_13936\1025655283.py:1: FutureWarning: The provided callable <function mean at 0x0000021E84557420> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd_2 = m.pivot_table(index='type', columns='Size', values='Price', aggfunc=np.mean)

Size         L      M      S     XL    XXL
type
Polo     700.0  600.0  500.0  800.0  900.0
T-shirt  500.0  400.0  300.0  600.0  700.0

In [7]:
pd_3 = m.pivot_table(index='Size', columns='type', values='Quantity', aggfunc=np.mean)
pd_3

C:\Users\shash\AppData\Local\Temp\ipykernel_13936\2183901139.py:1: FutureWarning: The provided callable <function mean at 0x0000021E84557420> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd_3 = m.pivot_table(index='Size', columns='type', values='Quantity', aggfunc=np.mean)

type  Polo  T-shirt
Size
L     15.0     40.0
M     10.0     35.0
S      5.0     30.0
XL    20.0     45.0
XXL   25.0     50.0

In [8]:
pd_1.index

Index(['L', 'M', 'S', 'XL', 'XXL'], dtype='object', name='Size')

In [9]:
pd_3.idxmax()

type
Polo       XXL
T-shirt    XXL
dtype: object

In [10]:
pd_1.idxmin()

type
Polo       S
T-shirt    S
dtype: object

In [11]:
pd_4 = pd.pivot_table(m, index=['Size','type'], columns='Quantity', aggfunc=np.median, fill_value=0)
pd_4

C:\Users\shash\AppData\Local\Temp\ipykernel_13936\212733496.py:1: FutureWarning: The provided callable <function median at 0x0000021E9A690CC0> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  pd_4 = pd.pivot_table(m, index=['Size','type'], columns='Quantity', aggfunc=np.median, fill_value=0)

              Price                                                          \
Quantity         5      10     15     20     25     30     35     40     45
Size type
L    Polo       0.0    0.0  700.0    0.0    0.0    0.0    0.0    0.0    0.0
     T-shirt    0.0    0.0    0.0    0.0    0.0    0.0    0.0  500.0    0.0
M    Polo       0.0  600.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
     T-shirt    0.0    0.0    0.0    0.0    0.0    0.0  400.0    0.0    0.0
S    Polo     500.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
     T-shirt    0.0    0.0    0.0    0.0    0.0  300.0    0.0    0.0    0.0
XL   Polo       0.0    0.0    0.0  800.0    0.0    0.0    0.0    0.0    0.0
     T-shirt    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  600.0
XXL  Polo       0.0    0.0    0.0    0.0  900.0    0.0    0.0    0.0    0.0
     T-shirt    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0


Quantity         50
Size type
L    Polo       0.0
     T-shirt    0.0
M    Polo       0.0
     T-shirt    0.0
S    Polo       0.0
     T-shirt    0.0
XL   Polo       0.0
     T-shirt    0.0
XXL  Polo       0.0
     T-shirt  700.0

In [12]:
m.sum(axis=0)  #column wise sum

Size                                         SMLXLXXLSMLXLXXL
type        PoloPoloPoloPoloPoloT-shirtT-shirtT-shirtT-shi...
Price                                                    6000
Quantity                                                  275
dtype: object

In [13]:
m.isnull().mean(axis=0) #percentage of missing values in each column

Size        0.0
type        0.0
Price       0.0
Quantity    0.0
dtype: float64

In [14]:
m.isnull().sum(axis=0) #percentage of missing values in each column

Size        0
type        0
Price       0
Quantity    0
dtype: int64

In [15]:
m.describe() #statistical summary of dataframe

            Price   Quantity
count   10.000000  10.000000
mean   600.000000  27.500000
std    182.574186  15.138252
min    300.000000   5.000000
25%    500.000000  16.250000
50%    600.000000  27.500000
75%    700.000000  38.750000
max    900.000000  50.000000

In [16]:
m.Price.corr(m.Quantity) #correlation between numerical columns of dataframe

np.float64(-0.10050378152592122)