In [191]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [192]:
df = pd.read_csv("C:\\Users\\admin1\\Desktop\\Shashank\\SamsungInnovationCampus-AI-ML\\DataSets\\mail_data.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [193]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   str
 1   Message   5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

In [194]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [195]:
data = df.where((pd.notnull(df)), '')
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [196]:
data['category'] = data['Category'].apply(lambda x: 1 if x == 'ham' else 0)

In [197]:
print(data)

     Category                                            Message  category
0         ham  Go until jurong point, crazy.. Available only ...         1
1         ham                      Ok lar... Joking wif u oni...         1
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...         0
3         ham  U dun say so early hor... U c already then say...         1
4         ham  Nah I don't think he goes to usf, he lives aro...         1
...       ...                                                ...       ...
5567     spam  This is the 2nd time we have tried 2 contact u...         0
5568      ham               Will ü b going to esplanade fr home?         1
5569      ham  Pity, * was in mood for that. So...any other s...         1
5570      ham  The guy did some bitching but I acted like i'd...         1
5571      ham                         Rofl. Its true to its name         1

[5572 rows x 3 columns]

In [198]:
x = data['Message']
y = data['category']

In [199]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

In [200]:
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [201]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358

In [202]:
print(X_test_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7687 stored elements and shape (1115, 7431)>
  Coords	Values
  (0, 1)	0.2381316303003606
  (0, 9)	0.2852706805264544
  (0, 14)	0.26797874471323896
  (0, 20)	0.30668032384591537
  (0, 306)	0.23975986557206702
  (0, 405)	0.2381316303003606
  (0, 1041)	0.28016206931555726
  (0, 1082)	0.2451068436245027
  (0, 1361)	0.25132445289897426
  (0, 1405)	0.3176863938914351
  (0, 1549)	0.2646498848307188
  (0, 4386)	0.18353336340308998
  (0, 5213)	0.1988547357502182
  (0, 5373)	0.2365698724638063
  (0, 6920)	0.20571591693537986
  (0, 7271)	0.1940327008179069
  (1, 3491)	0.496093956101028
  (1, 4418)	0.3457696891316818
  (1, 4729)	0.22965776503163893
  (1, 6214)	0.3621564482127515
  (1, 6507)	0.26731535902873493
  (1, 6588)	0.3298937975962767
  (1, 6732)	0.42473488678029325
  (1, 7368)	0.29957800964520975
  (2, 201)	0.2824102268489399
  :	:
  (1110, 6591)	0.7327660015422193
  (1111, 2440)	0.4137350055985486
  (1111, 3227)	0.44384935772735523
  (1111, 6033)	0.4714849709283488
  (1111, 6787)	0.40050175714278885
  (1111, 7353)	0.4991205841293424
  (1112, 1109)	0.35334496762883244
  (1112, 1683)	0.4017087436272034
  (1112, 2329)	0.241856898377491
  (1112, 4170)	0.3307835623173863
  (1112, 5056)	0.2559183043595413
  (1112, 5695)	0.3381604952481646
  (1112, 5778)	0.22807428098549426
  (1112, 6297)	0.3056896872268727
  (1112, 6777)	0.32853717524096393
  (1112, 7071)	0.33558524648843113
  (1113, 2224)	0.33379592674353104
  (1113, 2852)	0.5956422931588335
  (1113, 3113)	0.3384083342515567
  (1113, 3281)	0.3323250860171953
  (1113, 3811)	0.2810308058655509
  (1113, 4038)	0.370235205294137
  (1113, 4080)	0.30459473619554067
  (1114, 4033)	0.8543942045002639
  (1114, 4557)	0.5196253874825217

In [203]:
# data_2 = df.where(df['Category'] == 'spam').dropna()
# data_2.head()

In [204]:
model = LogisticRegression()
model.fit(X_train_features, y_train)

LogisticRegression()

In [205]:
pred_on_training_data = model.predict(X_train_features)

acc_on_training_data = accuracy_score(y_train, pred_on_training_data)

In [206]:
print(y_train[:10])

3075    1
1787    1
1614    1
4304    1
3266    0
2413    0
4539    1
3000    1
2433    1
2403    1
Name: category, dtype: int64

In [207]:
print(pred_on_training_data[:10])

[1 1 1 1 0 0 1 1 1 1]

In [208]:
print("Accuracy Score of the trained data: " ,acc_on_training_data)

Accuracy Score of the trained data:  0.9676912721561588

In [ ]:
input_mail = ["Hi frnd, which is the best way to avoid misunderstanding with our beloved one is?"]